### ISSUE TITLE
/var/www/html/app: 80:80: command not found

### ISSUE THREAD

**Issue by semsphy** [laraedit/laraedit-docker#21]
I ran command: `docker run laraedit/laraedit -p 80:80 ~/test:/var/www/html/app` and I got error `/var/www/html/app: 80:80: command not found`

Any idea? Thanks

**Comment by lube8uy** [comment]
Hey, the instruction in the readme is wrong, this is the correct instruction:

docker run -p 80:80 ~/test:/var/www/html/app laraedit/laraedit

**Comment by ibourgeois** [comment]
good call, i have an alias set in my shell. not sure how i let that one slip by me, lol.

**Comment by semsphy** [comment]
The correct one is: 
`docker run -p 80:80 -v ~/test:/var/www/html/app laraedit/laraedit`
