### ISSUE TITLE
Mysql shouldn't be in the web/php container

### ISSUE THREAD

**Issue by AleksanderKoko** [laraedit/laraedit-docker#24]
I dont see the point of dockerizing Homestead in Docker if the nginx, php, mysql and everything from Homestead is on the same container. The whole point of docker is to have them in different containers.

**Comment by marceloandrader** [comment]
I agree, may be homestead can be written as a docker-compose.yml file, where you select what services you need.

**Comment by ibourgeois** [comment]
agreed... to an extent.

this container is only meant for development. it is not meant to be deployed/shipped to production as with traditional containers. my only intent for this container is for it to provide the same features as homestead with a much smaller footprint and very little configuration required.

there are plans to provide a docker compose solution in the near future...

**Comment by marceloandrader** [comment]
cool, the idea behind docker is to have dev/prod parity

**Comment by ibourgeois** [comment]
i am aware of that. 

most of the laravel devs that I have talked to do not use docker and weren't looking forward to the learning curve. i also wanted this to be a simple introduction to what docker is capable of as i start adding more features, and breaking the containers up and start confusing everyone!
