### ISSUE TITLE
development/production ?

### ISSUE THREAD

**Issue by hopewise** [laraedit/laraedit-docker#25]
One thing that is very important, as for the nginx server, it should not cache any file of any type when in development, otherwise, php artisan serve would be the way to go while development.

Is the files caching turned off for nginx?

**Comment by ibourgeois** [comment]
this line in the server block should take care of it: https://github.com/laraedit/laraedit-docker/blob/master/homestead#L18

if not, let me know and we shall figure this thing out! :smile:

**Comment by hopewise** [comment]
Thanks, it worked :)

On Mon, Mar 7, 2016 at 5:18 PM, Derek Bourgeois notifications@github.com
wrote:

> Closed #25 https://github.com/laraedit/laraedit-docker/issues/25.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/laraedit/laraedit-docker/issues/25#event-580274753.

## 

## 

## Kind Regards,

Samir Sabri
Software Architect& Developer
www.dcaclab.com
Jordan-Middle East
