### ISSUE TITLE
Where is "first" video

### ISSUE THREAD

**Issue by mikeerickson** [laraedit/laraedit-docker#34]
Hey There

During this video (see link below), you eluded to a previous video?   I am looking to get started using Docker (first time user)  Do you have a "getting started 101" type video?

https://laravel-news.com/2016/03/dockerized-version-of-laravel-homestead/

**Comment by ibourgeois** [comment]
@mikeerickson https://www.youtube.com/watch?v=ktIxZfaq4zo Although it is a very short overview of how to use the container. The video that was posted on Laravel-News was the longer, more in-depth version. 

That being said, if you are having any issues, or just have questions, let me know! I'll do my best to help you out.

**Comment by mikeerickson** [comment]
@iBourgeois no worries, I am now up and running w/ docker and Laravel.   No mas homestead :)
