### ISSUE TITLE
CLI access to MySQL 

### ISSUE THREAD

**Issue by mikeerickson** [laraedit/laraedit-docker#35]
I am trying to access MySQL from the docker instance (via docker-machine ssh)

When attempting to access MySQL it doesn't find 'mysql-

$ mysql -u -p

**Comment by ibourgeois** [comment]
try `mysql -u root` as `mysql -u -p` assumes the username is `-p`

**Comment by mikeerickson** [comment]
What I meant to say is that using MySQL it doesn't recognize command.  

$ mysql ... 
Not a command

**Comment by ibourgeois** [comment]
What commands are you typing to get into the container? I would need to replicate the issue in order to troubleshoot it. 

Any info you have would help. 

From my end, it's working fine on OS X, Ubuntu 16.04, and Windows 10; each using both Kitematic and the Docker CLI.

**Comment by mikeerickson** [comment]
@iBourgeois I dont have access to my computer at the moment.  How are YOU calling it on your end?

**Comment by ibourgeois** [comment]
If you are on Win/OSX, connect to the Docker machine first...

```
docker-machine ssh default
```

and then run:

```
docker exec -it laraedit bash

```

just replace `laraedit` with whatever you've named your container.

![laraedit-mysql](https://cloud.githubusercontent.com/assets/3633464/16251877/b672cf04-37f7-11e6-8970-68a83a1a5aa3.gif)

**Comment by sandrodz** [comment]
I'm running docker beta on OS X, mysql-client works just fine. This issue can be closed.

**Comment by ibourgeois** [comment]
Thanks @sandrodz
