### ISSUE TITLE
Where is persistent data saved?

### ISSUE THREAD

**Issue by sandrodz** [laraedit/laraedit-docker#38]
Where do you save mysql persistent data?

**Comment by ibourgeois** [comment]
By default MySQL data is stored in the container, without persistence. 

In the event you would like to persist your database(s), you would create a folder anywhere on your computer and mount it to `/var/lib/mysql` when running the Docker container.

**Comment by sandrodz** [comment]
Yes, the issue is #33

**Comment by ibourgeois** [comment]
Depending on your use case (ex - Kitematic), the folder you create may need to be somewhere inside your user profile directory.

**Comment by ibourgeois** [comment]
Got it.
